// <auto-generated />
using System;
using EFDemo.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDemo.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ef")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorEntityMovieEntity", b =>
                {
                    b.Property<Guid>("ActorsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MoviesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("MovieActors", "ef");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.ActorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Actors", "ef");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3287fdf8-856a-4dd3-b65e-1008ca55564c"),
                            CreatedDate = new DateTime(2021, 11, 28, 7, 15, 14, 676, DateTimeKind.Local).AddTicks(3695),
                            FirstName = "Buğrakarakağan",
                            LastName = "Yazıcı"
                        },
                        new
                        {
                            Id = new Guid("cb5ee94a-0699-4818-b19e-331208b1849a"),
                            CreatedDate = new DateTime(2021, 2, 5, 1, 37, 38, 960, DateTimeKind.Local).AddTicks(1794),
                            FirstName = "Elti",
                            LastName = "Öymen"
                        },
                        new
                        {
                            Id = new Guid("c3571b26-e811-4333-b98a-c7e2360c5c7d"),
                            CreatedDate = new DateTime(2025, 12, 8, 1, 20, 4, 647, DateTimeKind.Local).AddTicks(5024),
                            FirstName = "Baybiçen",
                            LastName = "Doğan "
                        },
                        new
                        {
                            Id = new Guid("0e0aeb30-94c1-4e0b-8bae-9d6c3c344ee2"),
                            CreatedDate = new DateTime(2025, 7, 7, 16, 14, 11, 986, DateTimeKind.Local).AddTicks(7289),
                            FirstName = "Kancı",
                            LastName = "Poyrazoğlu"
                        },
                        new
                        {
                            Id = new Guid("60d33f68-cd9c-4483-b420-27224623325d"),
                            CreatedDate = new DateTime(2021, 9, 24, 20, 9, 11, 271, DateTimeKind.Local).AddTicks(6718),
                            FirstName = "Bayrın",
                            LastName = "Topaloğlu"
                        },
                        new
                        {
                            Id = new Guid("22e68d68-2f9d-473d-b998-e466ccc79b5f"),
                            CreatedDate = new DateTime(2023, 6, 18, 15, 39, 16, 250, DateTimeKind.Local).AddTicks(772),
                            FirstName = "Adıgüzel",
                            LastName = "Poyrazoğlu"
                        },
                        new
                        {
                            Id = new Guid("b47cf0da-4979-4c27-b1d5-c491f128809d"),
                            CreatedDate = new DateTime(2025, 9, 26, 13, 31, 14, 586, DateTimeKind.Local).AddTicks(9933),
                            FirstName = "Beğboğa",
                            LastName = "Dizdar "
                        },
                        new
                        {
                            Id = new Guid("688cffe7-4199-43ff-b61d-bf1e0f7927ec"),
                            CreatedDate = new DateTime(2024, 6, 8, 9, 57, 36, 566, DateTimeKind.Local).AddTicks(8797),
                            FirstName = "Arsıl",
                            LastName = "Berberoğlu"
                        },
                        new
                        {
                            Id = new Guid("35797c12-f99b-4254-bd83-d93740fd1a9f"),
                            CreatedDate = new DateTime(2023, 1, 30, 23, 33, 29, 774, DateTimeKind.Local).AddTicks(2726),
                            FirstName = "Karaca",
                            LastName = "Adıvar"
                        },
                        new
                        {
                            Id = new Guid("3bf818db-bad3-4cf0-85f5-3580310e9110"),
                            CreatedDate = new DateTime(2025, 3, 18, 3, 56, 22, 533, DateTimeKind.Local).AddTicks(2736),
                            FirstName = "Bongul",
                            LastName = "Ertepınar"
                        },
                        new
                        {
                            Id = new Guid("e1263d08-a954-482d-9a96-27f7b8f9312d"),
                            CreatedDate = new DateTime(2023, 8, 5, 0, 39, 4, 208, DateTimeKind.Local).AddTicks(259),
                            FirstName = "Ergenekatun",
                            LastName = "Tekand"
                        },
                        new
                        {
                            Id = new Guid("bfaa5f01-fd24-457b-a844-26026904e52e"),
                            CreatedDate = new DateTime(2024, 8, 25, 19, 53, 38, 774, DateTimeKind.Local).AddTicks(3074),
                            FirstName = "Bozan",
                            LastName = "Alnıaçık"
                        },
                        new
                        {
                            Id = new Guid("421d4525-a5a5-4ca9-954c-126a9e319d28"),
                            CreatedDate = new DateTime(2024, 9, 12, 17, 4, 33, 467, DateTimeKind.Local).AddTicks(2739),
                            FirstName = "Baçman",
                            LastName = "Özberk"
                        },
                        new
                        {
                            Id = new Guid("0f8e97f4-30f2-4382-b6b2-e0e789e520b1"),
                            CreatedDate = new DateTime(2023, 12, 15, 17, 19, 15, 894, DateTimeKind.Local).AddTicks(7722),
                            FirstName = "Barımtay",
                            LastName = "Çamdalı"
                        },
                        new
                        {
                            Id = new Guid("c8f10a8f-b7c9-4efb-8c22-35213f9687d9"),
                            CreatedDate = new DateTime(2025, 10, 13, 19, 14, 14, 750, DateTimeKind.Local).AddTicks(5949),
                            FirstName = "Aşkın",
                            LastName = "Yıldızoğlu"
                        },
                        new
                        {
                            Id = new Guid("2e0a1bf5-4234-4a4e-ab46-6b721e951089"),
                            CreatedDate = new DateTime(2021, 4, 2, 16, 22, 18, 102, DateTimeKind.Local).AddTicks(5469),
                            FirstName = "Beğbars",
                            LastName = "Elçiboğa"
                        },
                        new
                        {
                            Id = new Guid("2c78b2f0-fc2c-44fb-bd90-30ec96f7e3c1"),
                            CreatedDate = new DateTime(2022, 2, 27, 8, 42, 7, 124, DateTimeKind.Local).AddTicks(4481),
                            FirstName = "Bulmaz",
                            LastName = "Yorulmaz"
                        },
                        new
                        {
                            Id = new Guid("5d15fef0-e89c-4eb2-a19f-e607436f118e"),
                            CreatedDate = new DateTime(2022, 10, 29, 1, 35, 27, 128, DateTimeKind.Local).AddTicks(5726),
                            FirstName = "Bağtaş",
                            LastName = "Atakol"
                        },
                        new
                        {
                            Id = new Guid("afbb1190-f53b-48f8-b3f2-cbd36ee280e2"),
                            CreatedDate = new DateTime(2022, 12, 21, 10, 33, 30, 594, DateTimeKind.Local).AddTicks(4005),
                            FirstName = "Ilaçın",
                            LastName = "Tunaboylu"
                        },
                        new
                        {
                            Id = new Guid("37c6d1cb-d778-491e-addc-0a804cd1575b"),
                            CreatedDate = new DateTime(2022, 11, 4, 5, 43, 36, 183, DateTimeKind.Local).AddTicks(924),
                            FirstName = "Bağaalp",
                            LastName = "Baturalp"
                        });
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.DirectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Directors", "ef");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Genres", "ef");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.MovieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies", "ef");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.MoviePhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviePhotos", "ef");
                });

            modelBuilder.Entity("ActorEntityMovieEntity", b =>
                {
                    b.HasOne("EFDemo.Infra.Entities.ActorEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDemo.Infra.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.MovieEntity", b =>
                {
                    b.HasOne("EFDemo.Infra.Entities.DirectorEntity", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDemo.Infra.Entities.GenreEntity", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.MoviePhotoEntity", b =>
                {
                    b.HasOne("EFDemo.Infra.Entities.MovieEntity", "Movie")
                        .WithMany("Photos")
                        .HasForeignKey("MovieId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.DirectorEntity", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.GenreEntity", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("EFDemo.Infra.Entities.MovieEntity", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
